name: first Workflow

on:
    workflow_dispatch
    

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo "step 1"

      - name: step2
        run: echo "step2"

  

 